// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://eiuwjkptcltpipqpbuid.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVpdXdqa3B0Y2x0cGlwcXBidWlkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzkxOTQwOTAsImV4cCI6MjA1NDc3MDA5MH0.km8yKJO8Y9UsMBpTqkGVQjWf33hMH8xazXjKs0EcB50";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);